version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
      - SECRET_TOKEN="secret"
    volumes:
      - '$PWD/mongo-scripts/:/docker-entrypoint-initdb.d/'
      - 'mongodb_data:/data/db'
    ports:
      - '27017:27017'
    restart: always
    command: mongod
  simple_event_sender:
    container_name: simple_event_sender
    restart: always
    build: .
    ports:
      - '9000:9000'
    links:
      - mongo
      - rabbitmq
    environment:
      WAIT_HOSTS: 'mongo:27017, rabbitmq:5672'
  rabbitmq:
    image: 'rabbitmq:3.7-management'
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - 'rabbitmqdata:/var/lib/rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword
volumes:
  mongodb_data:
    driver: local
  rabbitmqdata:
    driver: local
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /Users/dsanti/erm/simple-event-sender/views/
      o: bind
